module.exports = {
    roles: {
        worker: "worker",
        miner: "miner",
        hauler: "hauler",
        upgrader: "upgrader",
        scout: "scout",
        remoteBuilder: "r_Builder",
        remoteHauler: "r_Hauler",
        remoteMiner: "r_Miner",
        reserver: "reserver",
        defender: "defender",
    },
    maxWorkerLevel: 8,
    maxHaulerLevel: 10,
    maxUpgraderLevel: 6,
    maxRemoteBuilderLevel: 8,
    maxRemoteHaulerLevel: 12,
    maxBaseSpawnCapacity: 0.95,
};